version: '3'
services:
  server:
    build:
      context: ./server/
      dockerfile: ./Dockerfile
      args:
       - app_env=${DEV_MODE}
    volumes:
      - ./server/:/app/marvel-server
    environment:
      - NODE_ENV=development
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    expose:
      - ${APP_SERVER_PORT}
  client:
    build:
      context: ./client/
      dockerfile: ./Dockerfile
      args:
      - app_env=${DEV_MODE}
    volumes:
      - ./client/:/app/marvel-client
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    ports:
      - ${APP_CLIENT_PORT}:${APP_CLIENT_PORT}
    expose:
      - ${APP_CLIENT_PORT}
    depends_on:
      - server
