version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
      args:
        - app_env=${PROD_MODE}
    environment:
      - NODE_ENV=${PROD_MODE}
    restart: always
  client:
    build:
      context: ./client/
      dockerfile: ./Dockerfile
      args:
      - app_env=${PROD_MODE}
    environment:
    - NODE_ENV=${PROD_MODE}
    ports:
    - ${APP_CLIENT_PORT}:${APP_CLIENT_PORT}
    restart: always


